### ISSUE TITLE
api documentを作る

### ISSUE THREAD

**Issue by ucpr** [SoyBeansLab/daizu-online-judge-backend#38]
https://python-responder.org/en/latest/tour.html#openapi-schema-support

**Comment by ihch** [comment]
リンクの例のままでいくとドメインの定義にinfraの`responder.API`が入ってきて微妙な気持ち. 
```python
@api.schema("Pet")
class PetSchema(Schema):
    name = fields.Str()
```

ドメイン定義の方では今のtypingベースからmarshmallowベースの定義に変更.  
次に`src/infrastructure/swagger/`くらいを作ってそこで`api.add_schema()`でschema登録をするモジュールを作ると最初の問題は回避できそう

**Comment by ihch** [comment]
example: https://github.com/nemusou/responder_openapi/blob/master/app.py
responderの実装: https://github.com/taoufik07/responder/blob/master/responder/ext/schema/__init__.py

**Comment by ucpr** [comment]
なるほど👀
モジュール作るやつ、良さそう👍

**Comment by ihch** [comment]
#42

**Comment by ucpr** [comment]
引き継ぎます

**Comment by ucpr** [comment]
https://github.com/taoufik07/responder/pull/425
pr出した

**Comment by ucpr** [comment]
mergeされたらexampleの `add_scheme` のままでも動かせる
