### ISSUE TITLE
リソースの監視について

### ISSUE THREAD

**Issue by ucpr** [SoyBeansLab/daizu-online-judge-backend#5]

**Comment by ucpr** [comment]
- https://prometheus.io/
- https://github.com/prometheus/prometheus

**Comment by ucpr** [comment]
@nemusou サーバーのリソースとかってdaizu-onlin-judgeのadminで見れるべき？それとも別で立てるべきかな?

**Comment by nemusou** [comment]
これ遠い昔に話したような気もするけどadminに入れるんだっけ

**Comment by ucpr** [comment]
入れるみたいな話をした気もする🙄
でも一旦入れない方向でやっていこう〜(実装重くなるので)

**Comment by ucpr** [comment]
将来的にやりたいね、位の気持ちで
